# Site settings
title: JazzMean Instruments
email: jazzmeaninstruments@googlemail.com
url: https://jazzmeaninstruments.github.io
description: "We pride ourselves on producing custom made guitars, basses and straps with materials sourced from small businesses across the United Kingdom."
keywords: "your keywords, separated by commas"
skills: "Bespoke - Local - Affordable"
#skills: "Luthier - Leather Worker - Seamster"
meta_author: Dean Charles

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 714A82 #714A82
  primary-rgb: "113,74,130" #"113,74,130"
  secondary: 010101 #010101
  secondary-dark: 300941 #300941

# Footer settings
footer:
  copyright: JazzMean Instruments
  location: Colchester
  social: Around the Web
  credits: Credit

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jazzmeanuk
  - title: facebook
    url: https://facebook.com/jazzmeaninstruments
  - title: instagram
    url: https://instagram.com/jazzmeaninstruments

# Postal address (add as many lines as necessary)
address:
  - line: Colchester
  - line: Essex
  - line: United Kingdom

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
